name: Custom Java CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: runner / checkstyle
        uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning

      - name: Run unit tests
        run: ./gradlew test

      - name: Create JAR file
        run: ./gradlew jar

      - name: Deploy artifacts
        run: |
          # Replace this with your deployment commands
          # For example, if you want to deploy to a Maven repository:
          ./gradlew publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JAR
          path: build/libs/*.jar
